project:
  type: website

website:
  title: "Nature Recovery Metric"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Methods"
        contents:
          - Tuning in lcd refacteror.qmd

      - section: "Results"
        contents:
          - first summary of landscapes.qmd

number-depth: 0

format:
  html:
    toc: true
    toc-location: right
    toc-depth: 5
    toc-float: true
    theme: sandstone
    lightbox: true
    code-fold: true
    code-summary: "Show code"
    reference-location: margin
    anchor-sections: true
    embed-resources: true

fig-width: 10
fig-dpi: 300

execute:
  echo: false
  warning: false
  cache: true

editor: visual

prefer-html: true

bibliography: references.bib

css: style.css

comments:
  hypothesis:
    theme: clean